#!/usr/bin/env node
/* Flatten the @import chain into shippable single files.
   An offline consumer must not be handed eighteen requests, and
   `@import url(https:...)` is the exact pattern their build checks reject.
   Writes dist/ plus a CHECKSUMS file so a vendored copy can be verified. */

import { readFileSync, writeFileSync, mkdirSync, copyFileSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';

const SHARED = ['tokens/shared.css'];
const BASE   = [
  'base.css',
  'components/actions.css', 'components/forms.css', 'components/surfaces.css',
  'components/display.css', 'components/feedback.css',
  'patterns/shell.css',
];
const THEME = {
  day:   { fonts: ['fonts/day.css'], tokens: ['palette', 'gradients', 'semantic', 'elevation', 'type', 'surfaces'].map(n => `tokens/day/${n}.css`), extra: [] },
  night: { fonts: ['fonts/day.css', 'fonts/night.css'], tokens: ['palette', 'gradients', 'semantic', 'elevation', 'type', 'surfaces'].map(n => `tokens/night/${n}.css`), extra: ['ambient/ambient.css'] },
};

const version = JSON.parse(readFileSync('package.json', 'utf8')).version;
const read = (p) => readFileSync(`src/${p}`, 'utf8').trimEnd();

function banner(title) {
  return `/*! Ahimsa Design System v${version} — ${title}\n *  MIT. Fonts are SIL OFL-1.1; ship fonts/OFL-*.txt alongside them.\n *  https://ahimsa-design.riverma.com\n *  Generated by tools/build.mjs — edit src/, not this file. */\n`;
}
function bundle(title, files) {
  return banner(title) + files.map((p) => `\n/* ===== ${p} ===== */\n${read(p)}`).join('\n') + '\n';
}

mkdirSync('dist', { recursive: true });

const out = {
  'ahimsa-day.css':   bundle('Ahimsa Day',  [...THEME.day.fonts,   ...SHARED, ...THEME.day.tokens,   ...BASE]),
  'ahimsa-night.css': bundle('Ahimsa Night', [...THEME.night.fonts, ...SHARED, ...THEME.night.tokens, ...BASE, ...THEME.night.extra]),
  'ahimsa.css':       bundle('Day + Night', [
    ...new Set([...THEME.day.fonts, ...THEME.night.fonts]),
    ...SHARED, ...THEME.day.tokens, ...THEME.night.tokens, ...BASE, ...THEME.night.extra,
  ]),
};

const lines = [];
for (const [name, css] of Object.entries(out)) {
  writeFileSync(`dist/${name}`, css);
  const sha = createHash('sha256').update(css).digest('hex');
  lines.push(`${sha}  ${name}`);
  console.log(`dist/${name.padEnd(18)} ${String(css.length).padStart(7)} bytes`);
}
writeFileSync('dist/CHECKSUMS', lines.join('\n') + '\n');
console.log('dist/CHECKSUMS     written');

/* The docs site is served with docs/ as its root, so it needs its own copy
   of the bundle and the fonts. Both are generated; edit src/ and fonts/. */
mkdirSync('docs/fonts', { recursive: true });
copyFileSync('dist/ahimsa.css', 'docs/ahimsa.css');
for (const f of readdirSync('fonts')) copyFileSync(`fonts/${f}`, `docs/fonts/${f}`);
copyFileSync('src/ambient/aberration.svg', 'docs/aberration.svg');
console.log(`docs/ahimsa.css + docs/fonts/ (${readdirSync('fonts').length} files) synced`);

if (/@import\s+url\(\s*['"]?https?:/i.test(Object.values(out).join(''))) {
  console.error('FAIL — a remote @import reached dist/. Offline consumers would break.');
  process.exit(1);
}
